ALTER TABLE VEHICULOS
ADD COLUMN stock BIGINT NOT NULL DEFAULT 0;

UPDATE VEHICULOS
SET stock = 10
WHERE marca = 'HAVAL' AND modelo = 'JOLION HEV';

UPDATE VEHICULOS
SET stock = 5
WHERE marca = 'TESLA' AND modelo = 'Model 3';

UPDATE VEHICULOS
SET stock = 3
WHERE marca = 'CHEVROLET' AND modelo = 'Silverado';